disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - type_name
  - legacy_constructor
  - unused_setter_value
  - file_length
  - void_function_in_ternary

included:
  - Runnect-iOS
excluded:
  # AppDelegate, SceneDelegate file 무시
  - Runnect-iOS/Global/Supports/AppDelegate.swift
  - Runnect-iOS/Global/Supports/SceneDelegate.swift
  - Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift

force_cast: warning
