# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Runnect-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'NMapsMap'
	pod 'Kingfisher', '~> 7.0'
	pod 'SnapKit', '~> 5.6.0'
	pod 'Moya', '~> 15.0'
	pod 'Then'
	pod 'KakaoSDKCommon'
	pod 'KakaoSDKAuth'
	pod 'KakaoSDKUser'
	pod 'KakaoSDKShare'
	pod 'KakaoSDKTemplate'
	pod 'FirebaseDynamicLinks'
	pod 'KakaoSDKTalk'
	pod 'DropDown', :git => 'https://github.com/thingineeer/DropDown.git', :commit => '95ee36f7bd925d466033c2c169979f1c574bf3b9'
	pod 'CombineCocoa'
	pod 'FirebaseAnalytics'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	

	
end
  # Pods for Runnect-iOS

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end

end
