# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Runnect-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'NMapsMap'
	pod 'Kingfisher', '~> 7.0'
	pod 'SnapKit', '~> 5.6.0'
	pod 'Moya', '~> 15.0'
	pod 'Then'
	pod 'KakaoSDKCommon'
	pod 'KakaoSDKAuth'
	pod 'KakaoSDKUser'
	pod 'KakaoSDKShare'
	pod 'KakaoSDKTemplate'
	pod 'FirebaseDynamicLinks'
	pod 'CombineCocoa'
	

  # Pods for Runnect-iOS

end
