# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do


  ############# version #############


  desc "Set Marketing and Build version"
  lane :set_version do |version|
    increment_version_number(
      version_number: version[:version],
      xcodeproj: "./Runnect-iOS.xcodeproj"
    )
  
    increment_build_number(
      build_number: Time.new.strftime("%Y.%m%d.%H%M"), # 2023.0703.2100
      xcodeproj: "./Runnect-iOS.xcodeproj"
    )
  end

  
  ############# beta #############


  desc "Push a new beta build to TestFlight"
  lane :beta do |version|
    version = version[:version]

    match(
      type: "appstore",
      app_identifier: "com.runnect.Runnect-iOS",
      readonly: true
    )

    if version
      puts "버전 정보: #{version}"
      set_version(version: version)
    else 
      puts "버전 입력 X"
      increment_build_number(
        build_number: Time.new.strftime("%Y.%m%d.%H%M"),
        xcodeproj: "./Runnect-iOS.xcodeproj"
      )
    end

    build_app(workspace: "Runnect-iOS.xcworkspace", scheme: "Runnect-iOS")

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end



  ############# Device Management #############

  desc "Register Devices"
  lane :register_new_device do  |options|
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(devices: device_hash)
    match(type: "development", force_for_new_devices: true)
  end

  ############# match #############


  desc "Match all code signing"
  lane :match_read_only do
    match(
      type: "appstore",
      app_identifier: "com.runnect.Runnect-iOS",
      readonly: true
    )

    match(
      type: "development",
      app_identifier: "com.runnect.Runnect-iOS",
      readonly: true
    )
  end
end
